from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_ROOT = REPO_ROOT / "tests"
RUNTIME_ROOT = TESTS_ROOT / ".runtime"

E2E_PROFILE = "e2e"
INTEGRATION_PROFILE = "integration"

E2E_BACKEND_PORT = 5010
INTEGRATION_BACKEND_PORT = 5011
E2E_FRONTEND_PORT = 4173

PRIMARY_COMIC_ID = "JM100001"
PRIMARY_COMIC_ORIGINAL_ID = "100001"
PRIMARY_COMIC_TITLE = "E2E Comic Alpha"

SECONDARY_COMIC_ID = "JM100002"
SECONDARY_COMIC_ORIGINAL_ID = "100002"
SECONDARY_COMIC_TITLE = "E2E Comic Beta"

PRIMARY_VIDEO_ID = "JAVDB900001"
PRIMARY_VIDEO_TITLE = "Seed Video"
