from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_ROOT = REPO_ROOT / "tests"
RUNTIME_ROOT = TESTS_ROOT / ".runtime"

E2E_PROFILE = "e2e"
INTEGRATION_PROFILE = "integration"

E2E_BACKEND_PORT = 5010
INTEGRATION_BACKEND_PORT = 5011
E2E_FRONTEND_PORT = 4173

PRIMARY_COMIC_ID = "JM100001"
PRIMARY_COMIC_ORIGINAL_ID = "100001"
PRIMARY_COMIC_TITLE = "E2E Comic Alpha"

SECONDARY_COMIC_ID = "JM100002"
SECONDARY_COMIC_ORIGINAL_ID = "100002"
SECONDARY_COMIC_TITLE = "E2E Comic Beta"

THIRD_COMIC_ID = "JM100003"
THIRD_COMIC_ORIGINAL_ID = "100003"
THIRD_COMIC_TITLE = "E2E Comic Gamma"

FOURTH_COMIC_ID = "JM100004"
FOURTH_COMIC_ORIGINAL_ID = "100004"
FOURTH_COMIC_TITLE = "E2E Comic Delta"

FIFTH_COMIC_ID = "JM100005"
FIFTH_COMIC_ORIGINAL_ID = "100005"
FIFTH_COMIC_TITLE = "E2E Comic Epsilon"

PRIMARY_VIDEO_ID = "JAVDB900001"
PRIMARY_VIDEO_TITLE = "Seed Video"

SECONDARY_VIDEO_ID = "JAVDB900002"
SECONDARY_VIDEO_TITLE = "Seed Video Beta"

THIRD_VIDEO_ID = "JAVDB900003"
THIRD_VIDEO_TITLE = "Seed Video Gamma"
