from .comic_repository_impl import ComicJsonRepository
from .tag_repository_impl import TagJsonRepository, RecommendationTagJsonRepository
from .list_repository_impl import ListJsonRepository
from .config_repository_impl import ConfigJsonRepository
from .recommendation_repository_impl import RecommendationJsonRepository
