from .comic import comic_bp
from .tag import tag_bp
from .list import list_bp
from .config import config_bp
from .recommendation import recommendation_bp
from .backup import backup_bp
from .author import author_bp
from .video import video_bp
from .actor import actor_bp
from .sync import sync_bp
